### ISSUE TITLE
Proposal: loopback-falcor example?

### ISSUE THREAD

**Issue by Bohmaster** [jonathan-casarrubias/native-chat-example#6]
**What is Falcor?**

> Falcor is the innovative data platform that powers the Netflix UIs. Falcor allows you to model all your backend data as a single Virtual JSON object on your Node server. On the client you work with your remote JSON object using familiar JavaScript operations like get, set, and call. If you know your data, you know your API.
> 
> Falcor is middleware. It is not a replacement for your application server, database, or MVC framework. Instead Falcor can be used to optimize communication between the layers of a new or existing application.
> 
> https://netflix.github.io/falcor/starter/what-is-falcor.html

Falcor-express module: 

> https://github.com/Netflix/falcor-express

I think this is a great feature. Netflix is using it actively.

**Comment by jonathan-casarrubias** [comment]
@Bohmaster this seems really nice, it is some sort of graphql.

Unfortunately this is not in the scope of the NativeChat Example, I think you may add an issue for this directly in the LoopBack repository for official, but I think that if I dig on it I could even provide community support, but I think it would be low priority since Angular Universal will be the next top priority.

Cheers
Jon!

**Comment by Bohmaster** [comment]
I understand and agree that angular universal is most important. I'll take a look at this personally and let you know what I get from it.
